module.exports = {
  apps: [
    {
      name: 'crm-pilot-backend',
      cwd: '/home/krttpt/crm/backend',
      script: 'index.js',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'production',
      },
      out_file: '/home/krttpt/crm/logs/backend.out.log',
      error_file: '/home/krttpt/crm/logs/backend.err.log',
      merge_logs: true,
      time: true,
    },
    {
      name: 'crm-pilot-frontend',
      cwd: '/home/krttpt/crm/frontend',
      script: 'node_modules/next/dist/bin/next',
      args: 'start -p 4013',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'production',
        PORT: '4013',
      },
      out_file: '/home/krttpt/crm/logs/frontend.out.log',
      error_file: '/home/krttpt/crm/logs/frontend.err.log',
      merge_logs: true,
      time: true,
    },
  ],
};
