module.exports = {
  apps: [
    {
      name: 'crm-pilot-backend',
      cwd: '/home/krttpt/crm/backend',
      script: 'index.js',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'production',
      },
      out_file: '/home/krttpt/crm/logs/backend.out.log',
      error_file: '/home/krttpt/crm/logs/backend.err.log',
      merge_logs: true,
      time: true,
    },
    {
      name: 'crm-lotus-sync',
      cwd: '/home/krttpt/crm/backend',
      script: 'services/lotusSync.js',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      env: { NODE_ENV: 'production' },
      out_file: '/home/krttpt/crm/logs/lotus-sync.out.log',
      error_file: '/home/krttpt/crm/logs/lotus-sync.err.log',
      merge_logs: true,
      time: true,
    },
    {
      name: 'crm-pilot-frontend',
      cwd: '/home/krttpt/crm/frontend',
      script: 'node_modules/next/dist/bin/next',
      args: 'start -p 4013',
      exec_mode: 'fork',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '512M',
      env: {
        NODE_ENV: 'production',
        PORT: '4013',
      },
      out_file: '/home/krttpt/crm/logs/frontend.out.log',
      error_file: '/home/krttpt/crm/logs/frontend.err.log',
      merge_logs: true,
      time: true,
    },
    {
      // Daily AI chat analysis: pre-warm Tier A analyst report for leads
      // active in the last 7 days with >=4 inbound msgs. One-shot script;
      // cron_restart re-runs it daily at 02:00 WIB (server TZ = Asia/Jakarta).
      name: 'crm-analyst-prewarm',
      cwd: '/home/krttpt/crm/backend',
      script: 'cron_analyst_tier_a_prewarm.js',
      exec_mode: 'fork',
      instances: 1,
      autorestart: false,
      cron_restart: '0 2 * * *',
      watch: false,
      env: { NODE_ENV: 'production' },
      out_file: '/home/krttpt/crm/logs/analyst-prewarm.out.log',
      error_file: '/home/krttpt/crm/logs/analyst-prewarm.err.log',
      merge_logs: true,
      time: true,
    },
    {
      name: 'crm-qna-harvest',
      cwd: '/home/krttpt/crm/backend',
      script: 'scripts/harvestQna.js',
      exec_mode: 'fork',
      instances: 1,
      autorestart: false,
      cron_restart: '30 2 * * *',
      watch: false,
      env: { NODE_ENV: 'production' },
      out_file: '/home/krttpt/crm/logs/qna-harvest.out.log',
      error_file: '/home/krttpt/crm/logs/qna-harvest.err.log',
      merge_logs: true,
      time: true,
    },
  ],
};
