-- Seed 30 synthetic customer questions covering main intents.
INSERT INTO crm_synthetic_questions (category, question, expected_intent) VALUES
  ('order_intent', 'Mau pesan bunga papan duka cita untuk besok ke Bekasi, budget 1 juta', 'order_intent'),
  ('order_intent', 'Bouquet mawar merah untuk ulang tahun istri', 'order_intent'),
  ('order_intent', 'Saya butuh parsel grand opening kantor besok pagi', 'order_intent'),
  ('order_intent', 'Mau order cake ulang tahun untuk anak', 'order_intent'),
  ('order_intent', 'Tolong buatkan rangkaian congratulations untuk kolega', 'order_intent'),
  ('order_status', 'Pesanan saya nomor 12345 sudah sampai belum?', 'order_status'),
  ('order_status', 'Saya order kemarin, sekarang status apa ya?', 'order_status'),
  ('order_status', 'Bunga belum sampai padahal sudah jam 3 sore', 'order_status'),
  ('shipping', 'Berapa ongkir ke Bandung?', 'shipping'),
  ('shipping', 'Bisa kirim same day ke Bekasi?', 'shipping'),
  ('shipping', 'Kalau Surabaya bisa nggak?', 'shipping'),
  ('shipping', 'Mau kirim ke Tangerang Selatan, ongkir berapa?', 'shipping'),
  ('pricing', 'Harga papan duka cita berapaan ya?', 'pricing'),
  ('pricing', 'Range harga bouquet mawar', 'pricing'),
  ('pricing', 'Yang paling murah berapa?', 'pricing'),
  ('payment', 'Bisa transfer BCA?', 'payment'),
  ('payment', 'Boleh COD?', 'payment'),
  ('payment', 'Saya sudah transfer, bagaimana?', 'payment'),
  ('faq', 'Buka jam berapa?', 'faq'),
  ('faq', 'Lokasi toko di mana?', 'faq'),
  ('faq', 'Bisa custom design sendiri?', 'faq'),
  ('faq', 'Berapa lama bunga bertahan?', 'faq'),
  ('complaint', 'Bunga yang kemarin layu, kecewa banget', 'complaint'),
  ('complaint', 'Pesanan salah alamat, mau komplain', 'complaint'),
  ('refund', 'Saya mau refund pesanan saya', 'refund'),
  ('cancel', 'Tolong cancel order saya', 'cancel'),
  ('explicit_request_human', 'Bisa bicara dengan manusia?', 'explicit_request_human'),
  ('explicit_request_human', 'Saya mau ngomong langsung dengan customer service', 'explicit_request_human'),
  ('other', 'Halo, saya cuma mau tanya-tanya', 'other'),
  ('other', 'Kerjasama gimana ya?', 'other')
ON CONFLICT DO NOTHING;
