-- 032_sales_identity_seed.sql
-- Seeded from lotus.contacts assignees with ≥5 contacts in last 60d (60d window ending 2026-06-14).
INSERT INTO crm_sales_identity (sales_key, display_name, brand, lotus_user_id, is_active) VALUES
  ('nanaars2', 'NanaARS2', 'prestisa', 407, true),
  ('lissaars1', 'LissaARS1', 'prestisa', 512, true),
  ('cindi14', 'Cindi14', 'prestisa', 178, true),
  ('telle_rb', 'Telle RB', 'rangkaianbunga', 767, true),
  ('data_cancel_rb', 'Data Cancel RB', 'rangkaianbunga', 696, true),
  ('tele_administrator', 'tele administrator', 'prestisa', 670, true),
  ('admin_data_cancel', 'admin data cancel', 'prestisa', 595, true),
  ('adminmita', 'AdminMita', 'prestisa', 698, true),
  ('hanifa35', 'Hanifa35', 'prestisa', 382, true),
  ('vinanda3', 'VINANDA3', 'prestisa', 108, true),
  ('raihanika11', 'RAIHANIKA11', 'prestisa', 161, true),
  ('anis1', 'ANIS1', 'prestisa', 106, true),
  ('iis31', 'IIS31', 'prestisa', 378, true),
  ('agung2', 'AGUNG2', 'prestisa', 107, true),
  ('anmita26', 'Anmita26', 'prestisa', 372, true),
  ('intanfresh2', 'IntanFresh2', 'prestisa', 483, true),
  ('vaniafresh1', 'VaniaFresh1', 'prestisa', 477, true),
  ('michellefresh4', 'MichelleFresh4', 'prestisa', 558, true),
  ('silfifresh5', 'SilfiFresh5', 'prestisa', 619, true),
  ('stefifresh3', 'StefiFresh3', 'prestisa', 508, true),
  ('telemarketing_potensial', 'Telemarketing Potensial', 'prestisa', 488, true),
  ('telemarketing_dapen', 'TELEMARKETING DAPEN', 'prestisa', 314, true),
  ('telemarketingparcel', 'telemarketingparcel', 'prestisa', 511, true),
  ('telemarketing_39', 'telemarketing 39', 'prestisa', 395, true),
  ('telemarketing_42', 'telemarketing 42', 'prestisa', 398, true),
  ('telemarketing_37', 'telemarketing 37', 'prestisa', 384, true),
  ('telemarketing_41', 'telemarketing 41', 'parselia', 397, true),
  ('telemarketing_30', 'telemarketing 30', 'prestisa', 377, true),
  ('telemarketing_38', 'telemarketing 38', 'prestisa', 394, true),
  ('telemarketing_29', 'telemarketing 29', 'prestisa', 376, true),
  ('telemarketing25', 'telemarketing25', 'prestisa', 371, true),
  ('telemarketing_27', 'telemarketing 27', 'prestisa', 374, true),
  ('telemarketing_32', 'telemarketing 32', 'prestisa', 379, true),
  ('telemarketingparcel2', 'telemarketingparcel2', 'prestisa', 548, true),
  ('telemarketing_33', 'telemarketing 33', 'prestisa', 380, true),
  ('telemarketing23', 'telemarketing23', 'prestisa', 369, true),
  ('telemarketing5', 'TELEMARKETING5', 'prestisa', 140, true),
  ('telemarketing21', 'telemarketing21', 'prestisa', 367, true),
  ('telemarketing9', 'TELEMARKETING9', 'prestisa', 159, true),
  ('telemarketing_28', 'telemarketing 28', 'prestisa', 375, true),
  ('telemarketing22', 'telemarketing22', 'prestisa', 368, true),
  ('telemarketing24', 'telemarketing24', 'prestisa', 370, true),
  ('telemarketing_34', 'telemarketing 34', 'prestisa', 381, true),
  ('telemarketing12', 'TELEMARKETING12', 'prestisa', 176, true),
  ('telemarketing_36', 'telemarketing 36', 'prestisa', 383, true),
  ('telemarketing_potensial_2', 'Telemarketing Potensial 2', 'prestisa', 489, true),
  ('telemarketing4', 'TELEMARKETING4', 'prestisa', 89, true),
  ('telemarketing10', 'TELEMARKETING10', 'prestisa', 160, true),
  ('recycle2', 'recycle2', 'prestisa', 268, true),
  ('adminsandra', 'AdminSandra', NULL, 699, true),
  ('ira_so', 'Ira SO', 'prestisa', 660, true),
  ('natasha_purchase', 'Natasha purchase', NULL, 646, true),
  ('sales_data_cancel_7', 'Sales Data Cancel 7', 'prestisa', 651, true),
  ('sales_data_cancel_8', 'Sales Data Cancel 8', 'prestisa', 652, true),
  ('sales_data_cancel_4', 'Sales Data Cancel 4', 'prestisa', 564, true),
  ('sales_data_cancel_3', 'Sales Data Cancel 3', 'prestisa', 563, true),
  ('yana', 'Yana', 'prestisa', 142, true),
  ('eka_sales_rb', 'Eka Sales RB', 'rangkaianbunga', 668, true),
  ('sales_data_cancel_6', 'Sales Data Cancel 6', 'prestisa', 594, true),
  ('sales_data_cancel_2', 'Sales Data Cancel 2', 'prestisa', 562, true),
  ('sales_data_cancel_1', 'Sales Data Cancel 1', 'prestisa', 561, true),
  ('sales_data_cancel_5', 'Sales Data Cancel 5', 'prestisa', 565, true),
  ('salma_rb', 'Salma RB', 'rangkaianbunga', 741, true),
  ('sisy', 'sisy', NULL, 84, true),
  ('sales_rangkaian_bunga', 'Sales Rangkaian Bunga', 'rangkaianbunga', 653, true),
  ('recycle3', 'recycle3', 'prestisa', 269, true),
  ('parselia_2', 'parselia 2', 'parselia', 132, true),
  ('mentari_rb', 'Mentari RB', 'rangkaianbunga', 666, true),
  ('chrstina', 'Chrstina', NULL, 49, true),
  ('rafi', 'Rafi', 'prestisa', 258, true),
  ('agung_so', 'Agung SO', 'prestisa', 421, true),
  ('seffy', 'Seffy', 'prestisa', 618, true),
  ('parselia', 'parselia', 'parselia', 113, true),
  ('jeje_bd', 'jeje_bd', NULL, 363, true),
  ('septi_so', 'Septi SO', 'prestisa', 629, true),
  ('loveftw', 'loveftw', NULL, 99, true),
  ('rani7', 'RANI7', 'prestisa', 146, true),
  ('recycle1', 'recycle1', 'prestisa', 267, true),
  ('lutfia_so', 'Lutfia SO', 'prestisa', 724, true),
  ('tania_rb', 'Tania RB', 'rangkaianbunga', 836, true),
  ('agrita', 'agrita', NULL, 693, true),
  ('rama_so_rb', 'Rama SO RB', 'rangkaianbunga', 737, true),
  ('fitria_sales_rb', 'Fitria Sales RB', 'rangkaianbunga', 662, true),
  ('yuli_karina', 'Yuli Karina', 'rangkaianbunga', 665, true),
  ('tami_so', 'Tami SO', 'prestisa', 824, true),
  ('pkl_1_tele', 'pkl 1 tele', 'prestisa', 788, true),
  ('nenden_dacen', 'Nenden Dacen', 'prestisa', 412, true),
  ('sales_training_2', 'Sales Training 2', 'prestisa', 523, true),
  ('salma_so', 'Salma SO', 'prestisa', 661, true),
  ('recycle4', 'recycle4', 'prestisa', 276, true),
  ('agung_dacen', 'Agung dacen', 'prestisa', 411, true),
  ('virdha_so', 'Virdha SO', 'prestisa', 580, true),
  ('farah_dacen', 'farah dacen', 'prestisa', 419, true),
  ('telemarketing19', 'TELEMARKETING19', 'prestisa', 183, true),
  ('farhan_rb', 'Farhan RB', 'rangkaianbunga', 740, true),
  ('sales_training_4', 'Sales Training 4', 'rangkaianbunga', 529, true),
  ('angin_rb', 'Angin RB', 'rangkaianbunga', 760, true),
  ('farhan_so', 'farhan so', 'prestisa', 553, true),
  ('ayu_dacen', 'Ayu Dacen', 'prestisa', 413, true),
  ('hade', 'HADE', 'prestisa', 291, true),
  ('hanun_so', 'Hanun SO', 'prestisa', 530, true)
ON CONFLICT (sales_key) DO NOTHING;
